# Uses the docker build step to build an image called msa
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/msa', '.']

# msa is pushed to Container Registry
images:
- 'gcr.io/$PROJECT_ID/msa'